# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

import types

__config__ = pulumi.Config('planetscale')


class _ExportableConfig(types.ModuleType):
    @property
    def access_token(self) -> Optional[str]:
        """
        Name of the service token to use. Alternatively, use `PLANETSCALE_SERVICE_TOKEN_NAME`. Mutually exclusive with
        `service_token_name` and `service_token`.
        """
        return __config__.get('accessToken')

    @property
    def endpoint(self) -> Optional[str]:
        """
        If set, points the API client to a different endpoint than `https:://api.planetscale.com/v1`.
        """
        return __config__.get('endpoint')

    @property
    def service_token(self) -> Optional[str]:
        """
        Value of the service token to use. Alternatively, use `PLANETSCALE_SERVICE_TOKEN`. Mutually exclusive with
        `access_token`.
        """
        return __config__.get('serviceToken')

    @property
    def service_token_name(self) -> Optional[str]:
        """
        Name of the service token to use. Alternatively, use `PLANETSCALE_SERVICE_TOKEN_NAME`. Mutually exclusive with
        `access_token`.
        """
        return __config__.get('serviceTokenName')

