// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Planetscale
{
    public static class GetBranches
    {
        /// <summary>
        /// A list of PlanetScale branches.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Planetscale = Pulumi.Planetscale;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Planetscale.GetBranches.Invoke(new()
        ///     {
        ///         Organization = "example.com",
        ///         Database = "example_db",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["branches"] = example,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetBranchesResult> InvokeAsync(GetBranchesArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetBranchesResult>("planetscale:index/getBranches:getBranches", args ?? new GetBranchesArgs(), options.WithDefaults());

        /// <summary>
        /// A list of PlanetScale branches.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Planetscale = Pulumi.Planetscale;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Planetscale.GetBranches.Invoke(new()
        ///     {
        ///         Organization = "example.com",
        ///         Database = "example_db",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["branches"] = example,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetBranchesResult> Invoke(GetBranchesInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetBranchesResult>("planetscale:index/getBranches:getBranches", args ?? new GetBranchesInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// A list of PlanetScale branches.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Planetscale = Pulumi.Planetscale;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Planetscale.GetBranches.Invoke(new()
        ///     {
        ///         Organization = "example.com",
        ///         Database = "example_db",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["branches"] = example,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetBranchesResult> Invoke(GetBranchesInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetBranchesResult>("planetscale:index/getBranches:getBranches", args ?? new GetBranchesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetBranchesArgs : global::Pulumi.InvokeArgs
    {
        [Input("database", required: true)]
        public string Database { get; set; } = null!;

        [Input("organization", required: true)]
        public string Organization { get; set; } = null!;

        public GetBranchesArgs()
        {
        }
        public static new GetBranchesArgs Empty => new GetBranchesArgs();
    }

    public sealed class GetBranchesInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("database", required: true)]
        public Input<string> Database { get; set; } = null!;

        [Input("organization", required: true)]
        public Input<string> Organization { get; set; } = null!;

        public GetBranchesInvokeArgs()
        {
        }
        public static new GetBranchesInvokeArgs Empty => new GetBranchesInvokeArgs();
    }


    [OutputType]
    public sealed class GetBranchesResult
    {
        public readonly ImmutableArray<Outputs.GetBranchesBranchResult> Branches;
        public readonly string Database;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Organization;

        [OutputConstructor]
        private GetBranchesResult(
            ImmutableArray<Outputs.GetBranchesBranchResult> branches,

            string database,

            string id,

            string organization)
        {
            Branches = branches;
            Database = database;
            Id = id;
            Organization = organization;
        }
    }
}
