// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Planetscale
{
    public static class GetBranchSchema
    {
        /// <summary>
        /// The schema of a PlanetScale branch.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Planetscale = Pulumi.Planetscale;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Planetscale.GetBranchSchema.Invoke(new()
        ///     {
        ///         Organization = "example.com",
        ///         Database = "example_db",
        ///         Branch = "main",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["branchSchema"] = example,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetBranchSchemaResult> InvokeAsync(GetBranchSchemaArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetBranchSchemaResult>("planetscale:index/getBranchSchema:getBranchSchema", args ?? new GetBranchSchemaArgs(), options.WithDefaults());

        /// <summary>
        /// The schema of a PlanetScale branch.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Planetscale = Pulumi.Planetscale;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Planetscale.GetBranchSchema.Invoke(new()
        ///     {
        ///         Organization = "example.com",
        ///         Database = "example_db",
        ///         Branch = "main",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["branchSchema"] = example,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetBranchSchemaResult> Invoke(GetBranchSchemaInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetBranchSchemaResult>("planetscale:index/getBranchSchema:getBranchSchema", args ?? new GetBranchSchemaInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// The schema of a PlanetScale branch.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Planetscale = Pulumi.Planetscale;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Planetscale.GetBranchSchema.Invoke(new()
        ///     {
        ///         Organization = "example.com",
        ///         Database = "example_db",
        ///         Branch = "main",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["branchSchema"] = example,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetBranchSchemaResult> Invoke(GetBranchSchemaInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetBranchSchemaResult>("planetscale:index/getBranchSchema:getBranchSchema", args ?? new GetBranchSchemaInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetBranchSchemaArgs : global::Pulumi.InvokeArgs
    {
        [Input("branch", required: true)]
        public string Branch { get; set; } = null!;

        [Input("database", required: true)]
        public string Database { get; set; } = null!;

        [Input("keyspace")]
        public string? Keyspace { get; set; }

        [Input("organization", required: true)]
        public string Organization { get; set; } = null!;

        public GetBranchSchemaArgs()
        {
        }
        public static new GetBranchSchemaArgs Empty => new GetBranchSchemaArgs();
    }

    public sealed class GetBranchSchemaInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("branch", required: true)]
        public Input<string> Branch { get; set; } = null!;

        [Input("database", required: true)]
        public Input<string> Database { get; set; } = null!;

        [Input("keyspace")]
        public Input<string>? Keyspace { get; set; }

        [Input("organization", required: true)]
        public Input<string> Organization { get; set; } = null!;

        public GetBranchSchemaInvokeArgs()
        {
        }
        public static new GetBranchSchemaInvokeArgs Empty => new GetBranchSchemaInvokeArgs();
    }


    [OutputType]
    public sealed class GetBranchSchemaResult
    {
        public readonly string Branch;
        public readonly string Database;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string? Keyspace;
        public readonly string Organization;
        public readonly ImmutableArray<Outputs.GetBranchSchemaTableResult> Tables;

        [OutputConstructor]
        private GetBranchSchemaResult(
            string branch,

            string database,

            string id,

            string? keyspace,

            string organization,

            ImmutableArray<Outputs.GetBranchSchemaTableResult> tables)
        {
            Branch = branch;
            Database = database;
            Id = id;
            Keyspace = keyspace;
            Organization = organization;
            Tables = tables;
        }
    }
}
