// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Planetscale
{
    public static class GetBranchSchemaLint
    {
        /// <summary>
        /// Linting errors for the schema of a PlanetScale branch.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Planetscale = Pulumi.Planetscale;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Planetscale.GetBranchSchemaLint.Invoke(new()
        ///     {
        ///         Organization = "example.com",
        ///         Database = "example_db",
        ///         Branch = "main",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["schemaLint"] = example,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetBranchSchemaLintResult> InvokeAsync(GetBranchSchemaLintArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetBranchSchemaLintResult>("planetscale:index/getBranchSchemaLint:getBranchSchemaLint", args ?? new GetBranchSchemaLintArgs(), options.WithDefaults());

        /// <summary>
        /// Linting errors for the schema of a PlanetScale branch.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Planetscale = Pulumi.Planetscale;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Planetscale.GetBranchSchemaLint.Invoke(new()
        ///     {
        ///         Organization = "example.com",
        ///         Database = "example_db",
        ///         Branch = "main",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["schemaLint"] = example,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetBranchSchemaLintResult> Invoke(GetBranchSchemaLintInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetBranchSchemaLintResult>("planetscale:index/getBranchSchemaLint:getBranchSchemaLint", args ?? new GetBranchSchemaLintInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Linting errors for the schema of a PlanetScale branch.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Planetscale = Pulumi.Planetscale;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Planetscale.GetBranchSchemaLint.Invoke(new()
        ///     {
        ///         Organization = "example.com",
        ///         Database = "example_db",
        ///         Branch = "main",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["schemaLint"] = example,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetBranchSchemaLintResult> Invoke(GetBranchSchemaLintInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetBranchSchemaLintResult>("planetscale:index/getBranchSchemaLint:getBranchSchemaLint", args ?? new GetBranchSchemaLintInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetBranchSchemaLintArgs : global::Pulumi.InvokeArgs
    {
        [Input("branch", required: true)]
        public string Branch { get; set; } = null!;

        [Input("database", required: true)]
        public string Database { get; set; } = null!;

        [Input("organization", required: true)]
        public string Organization { get; set; } = null!;

        public GetBranchSchemaLintArgs()
        {
        }
        public static new GetBranchSchemaLintArgs Empty => new GetBranchSchemaLintArgs();
    }

    public sealed class GetBranchSchemaLintInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("branch", required: true)]
        public Input<string> Branch { get; set; } = null!;

        [Input("database", required: true)]
        public Input<string> Database { get; set; } = null!;

        [Input("organization", required: true)]
        public Input<string> Organization { get; set; } = null!;

        public GetBranchSchemaLintInvokeArgs()
        {
        }
        public static new GetBranchSchemaLintInvokeArgs Empty => new GetBranchSchemaLintInvokeArgs();
    }


    [OutputType]
    public sealed class GetBranchSchemaLintResult
    {
        public readonly string Branch;
        public readonly string Database;
        public readonly ImmutableArray<Outputs.GetBranchSchemaLintErrorResult> Errors;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Organization;

        [OutputConstructor]
        private GetBranchSchemaLintResult(
            string branch,

            string database,

            ImmutableArray<Outputs.GetBranchSchemaLintErrorResult> errors,

            string id,

            string organization)
        {
            Branch = branch;
            Database = database;
            Errors = errors;
            Id = id;
            Organization = organization;
        }
    }
}
