// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Planetscale
{
    public static class GetDatabaseReadOnlyRegions
    {
        /// <summary>
        /// A list of PlanetScale read-only regions.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Planetscale = Pulumi.Planetscale;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Planetscale.GetDatabaseReadOnlyRegions.Invoke(new()
        ///     {
        ///         Organization = "example.com",
        ///         Name = "example_db",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["databaseRoRegions"] = examplePlanetscaleDatabaseRegions,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetDatabaseReadOnlyRegionsResult> InvokeAsync(GetDatabaseReadOnlyRegionsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDatabaseReadOnlyRegionsResult>("planetscale:index/getDatabaseReadOnlyRegions:getDatabaseReadOnlyRegions", args ?? new GetDatabaseReadOnlyRegionsArgs(), options.WithDefaults());

        /// <summary>
        /// A list of PlanetScale read-only regions.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Planetscale = Pulumi.Planetscale;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Planetscale.GetDatabaseReadOnlyRegions.Invoke(new()
        ///     {
        ///         Organization = "example.com",
        ///         Name = "example_db",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["databaseRoRegions"] = examplePlanetscaleDatabaseRegions,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetDatabaseReadOnlyRegionsResult> Invoke(GetDatabaseReadOnlyRegionsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDatabaseReadOnlyRegionsResult>("planetscale:index/getDatabaseReadOnlyRegions:getDatabaseReadOnlyRegions", args ?? new GetDatabaseReadOnlyRegionsInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// A list of PlanetScale read-only regions.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Planetscale = Pulumi.Planetscale;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Planetscale.GetDatabaseReadOnlyRegions.Invoke(new()
        ///     {
        ///         Organization = "example.com",
        ///         Name = "example_db",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["databaseRoRegions"] = examplePlanetscaleDatabaseRegions,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetDatabaseReadOnlyRegionsResult> Invoke(GetDatabaseReadOnlyRegionsInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetDatabaseReadOnlyRegionsResult>("planetscale:index/getDatabaseReadOnlyRegions:getDatabaseReadOnlyRegions", args ?? new GetDatabaseReadOnlyRegionsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDatabaseReadOnlyRegionsArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the database for which the read-only regions are available.
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        /// <summary>
        /// The organization for which the read-only regions are available.
        /// </summary>
        [Input("organization", required: true)]
        public string Organization { get; set; } = null!;

        public GetDatabaseReadOnlyRegionsArgs()
        {
        }
        public static new GetDatabaseReadOnlyRegionsArgs Empty => new GetDatabaseReadOnlyRegionsArgs();
    }

    public sealed class GetDatabaseReadOnlyRegionsInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the database for which the read-only regions are available.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// The organization for which the read-only regions are available.
        /// </summary>
        [Input("organization", required: true)]
        public Input<string> Organization { get; set; } = null!;

        public GetDatabaseReadOnlyRegionsInvokeArgs()
        {
        }
        public static new GetDatabaseReadOnlyRegionsInvokeArgs Empty => new GetDatabaseReadOnlyRegionsInvokeArgs();
    }


    [OutputType]
    public sealed class GetDatabaseReadOnlyRegionsResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of the database for which the read-only regions are available.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The organization for which the read-only regions are available.
        /// </summary>
        public readonly string Organization;
        /// <summary>
        /// The list of read-only regions available for the database.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetDatabaseReadOnlyRegionsRegionResult> Regions;

        [OutputConstructor]
        private GetDatabaseReadOnlyRegionsResult(
            string id,

            string name,

            string organization,

            ImmutableArray<Outputs.GetDatabaseReadOnlyRegionsRegionResult> regions)
        {
            Id = id;
            Name = name;
            Organization = organization;
            Regions = regions;
        }
    }
}
