// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Planetscale.Outputs
{

    [OutputType]
    public sealed class BackupBackupPolicy
    {
        /// <summary>
        /// When the backup policy was created.
        /// </summary>
        public readonly string? CreatedAt;
        /// <summary>
        /// The unit for the frequency of the backup policy. Not configurable for now.
        /// </summary>
        public readonly string? FrequencyUnit;
        /// <summary>
        /// A number value for the frequency of the backup policy. Not configurable for now.
        /// </summary>
        public readonly double? FrequencyValue;
        /// <summary>
        /// The ID of the backup policy.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// When the backup was last run.
        /// </summary>
        public readonly string? LastRanAt;
        /// <summary>
        /// The name of the backup policy.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// When the backup will next run.
        /// </summary>
        public readonly string? NextRunAt;
        /// <summary>
        /// The unit for the retention period of the backup policy.
        /// </summary>
        public readonly string RetentionUnit;
        /// <summary>
        /// A number value for the retention period of the backup policy.
        /// </summary>
        public readonly double RetentionValue;
        /// <summary>
        /// Day of the week that the backup is scheduled.
        /// </summary>
        public readonly string? ScheduleDay;
        /// <summary>
        /// Week of the month that the backup is scheduled.
        /// </summary>
        public readonly string? ScheduleWeek;
        /// <summary>
        /// Whether the backup policy is for a production or development database, or for a database branch.
        /// </summary>
        public readonly string? Target;
        /// <summary>
        /// When the backup policy was last updated.
        /// </summary>
        public readonly string? UpdatedAt;

        [OutputConstructor]
        private BackupBackupPolicy(
            string? createdAt,

            string? frequencyUnit,

            double? frequencyValue,

            string? id,

            string? lastRanAt,

            string? name,

            string? nextRunAt,

            string retentionUnit,

            double retentionValue,

            string? scheduleDay,

            string? scheduleWeek,

            string? target,

            string? updatedAt)
        {
            CreatedAt = createdAt;
            FrequencyUnit = frequencyUnit;
            FrequencyValue = frequencyValue;
            Id = id;
            LastRanAt = lastRanAt;
            Name = name;
            NextRunAt = nextRunAt;
            RetentionUnit = retentionUnit;
            RetentionValue = retentionValue;
            ScheduleDay = scheduleDay;
            ScheduleWeek = scheduleWeek;
            Target = target;
            UpdatedAt = updatedAt;
        }
    }
}
