// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Planetscale.Outputs
{

    [OutputType]
    public sealed class GetBackupsBackupResult
    {
        /// <summary>
        /// The actor that created the backup.
        /// </summary>
        public readonly Outputs.GetBackupsBackupActorResult Actor;
        /// <summary>
        /// The backup policy being followed.
        /// </summary>
        public readonly Outputs.GetBackupsBackupBackupPolicyResult BackupPolicy;
        /// <summary>
        /// The branch this backup belongs to.
        /// </summary>
        public readonly string Branch;
        /// <summary>
        /// When the backup was created.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// The database this backup belongs to.
        /// </summary>
        public readonly string Database;
        /// <summary>
        /// The estimated storage cost of the backup.
        /// </summary>
        public readonly double EstimatedStorageCost;
        /// <summary>
        /// The ID of the backup.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of the backup.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The organization this backup belongs to.
        /// </summary>
        public readonly string Organization;
        /// <summary>
        /// Whether or not the backup policy is required.
        /// </summary>
        public readonly bool Required;
        /// <summary>
        /// Branches that have been restored with this backup.
        /// </summary>
        public readonly ImmutableArray<string> RestoredBranches;
        /// <summary>
        /// The size of the backup.
        /// </summary>
        public readonly double Size;
        /// <summary>
        /// The current state of the backup.
        /// </summary>
        public readonly string State;
        /// <summary>
        /// When the backup was last updated.
        /// </summary>
        public readonly string UpdatedAt;

        [OutputConstructor]
        private GetBackupsBackupResult(
            Outputs.GetBackupsBackupActorResult actor,

            Outputs.GetBackupsBackupBackupPolicyResult backupPolicy,

            string branch,

            string createdAt,

            string database,

            double estimatedStorageCost,

            string id,

            string name,

            string organization,

            bool required,

            ImmutableArray<string> restoredBranches,

            double size,

            string state,

            string updatedAt)
        {
            Actor = actor;
            BackupPolicy = backupPolicy;
            Branch = branch;
            CreatedAt = createdAt;
            Database = database;
            EstimatedStorageCost = estimatedStorageCost;
            Id = id;
            Name = name;
            Organization = organization;
            Required = required;
            RestoredBranches = restoredBranches;
            Size = size;
            State = state;
            UpdatedAt = updatedAt;
        }
    }
}
