// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Planetscale.Outputs
{

    [OutputType]
    public sealed class GetBranchSchemaTableResult
    {
        /// <summary>
        /// Syntax highlighted HTML for the table's schema.
        /// </summary>
        public readonly string Html;
        /// <summary>
        /// Name of the table.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The table's schema.
        /// </summary>
        public readonly string Raw;

        [OutputConstructor]
        private GetBranchSchemaTableResult(
            string html,

            string name,

            string raw)
        {
            Html = html;
            Name = name;
            Raw = raw;
        }
    }
}
