// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Planetscale.Outputs
{

    [OutputType]
    public sealed class GetBranchSchemaLintErrorResult
    {
        /// <summary>
        /// A list of invalid auto-incremented columns.
        /// </summary>
        public readonly ImmutableArray<string> AutoIncrementColumnNames;
        /// <summary>
        /// The charset of the schema.
        /// </summary>
        public readonly string CharsetName;
        /// <summary>
        /// The name of the invalid check constraint.
        /// </summary>
        public readonly string CheckConstraintName;
        /// <summary>
        /// The column in a table relevant to the error.
        /// </summary>
        public readonly string ColumnName;
        /// <summary>
        /// A link to the documentation related to the error.
        /// </summary>
        public readonly string DocsUrl;
        /// <summary>
        /// The engine of the schema.
        /// </summary>
        public readonly string EngineName;
        /// <summary>
        /// The name of the invalid enum value.
        /// </summary>
        public readonly string EnumValue;
        /// <summary>
        /// A description for the error that occurred.
        /// </summary>
        public readonly string ErrorDescription;
        /// <summary>
        /// A list of invalid foreign key columns in a table.
        /// </summary>
        public readonly ImmutableArray<string> ForeignKeyColumnNames;
        /// <summary>
        /// The path for an invalid JSON column.
        /// </summary>
        public readonly string JsonPath;
        /// <summary>
        /// The keyspace of the schema with the error.
        /// </summary>
        public readonly string KeyspaceName;
        /// <summary>
        /// Code representing.
        /// </summary>
        public readonly string LintError;
        /// <summary>
        /// The name of the invalid partition in the schema.
        /// </summary>
        public readonly string PartitionName;
        /// <summary>
        /// The name of the invalid partitioning type.
        /// </summary>
        public readonly string PartitioningType;
        /// <summary>
        /// The subject for the errors.
        /// </summary>
        public readonly string SubjectType;
        /// <summary>
        /// The table with the error.
        /// </summary>
        public readonly string TableName;
        /// <summary>
        /// The name of the vindex for the schema.
        /// </summary>
        public readonly string VindexName;

        [OutputConstructor]
        private GetBranchSchemaLintErrorResult(
            ImmutableArray<string> autoIncrementColumnNames,

            string charsetName,

            string checkConstraintName,

            string columnName,

            string docsUrl,

            string engineName,

            string enumValue,

            string errorDescription,

            ImmutableArray<string> foreignKeyColumnNames,

            string jsonPath,

            string keyspaceName,

            string lintError,

            string partitionName,

            string partitioningType,

            string subjectType,

            string tableName,

            string vindexName)
        {
            AutoIncrementColumnNames = autoIncrementColumnNames;
            CharsetName = charsetName;
            CheckConstraintName = checkConstraintName;
            ColumnName = columnName;
            DocsUrl = docsUrl;
            EngineName = engineName;
            EnumValue = enumValue;
            ErrorDescription = errorDescription;
            ForeignKeyColumnNames = foreignKeyColumnNames;
            JsonPath = jsonPath;
            KeyspaceName = keyspaceName;
            LintError = lintError;
            PartitionName = partitionName;
            PartitioningType = partitioningType;
            SubjectType = subjectType;
            TableName = tableName;
            VindexName = vindexName;
        }
    }
}
