// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Planetscale.Outputs
{

    [OutputType]
    public sealed class GetDatabaseDataImportDataSourceResult
    {
        /// <summary>
        /// The name of the database imported from.
        /// </summary>
        public readonly string Database;
        /// <summary>
        /// The hostname where the database lives.
        /// </summary>
        public readonly string Hostname;
        /// <summary>
        /// The port on which the database listens on the host.
        /// </summary>
        public readonly string Port;

        [OutputConstructor]
        private GetDatabaseDataImportDataSourceResult(
            string database,

            string hostname,

            string port)
        {
            Database = database;
            Hostname = hostname;
            Port = port;
        }
    }
}
