// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Planetscale.Outputs
{

    [OutputType]
    public sealed class GetDatabaseDataImportResult
    {
        /// <summary>
        /// Connection information for the source of the data for the import.
        /// </summary>
        public readonly Outputs.GetDatabaseDataImportDataSourceResult DataSource;
        /// <summary>
        /// When the import finished.
        /// </summary>
        public readonly string FinishedAt;
        /// <summary>
        /// Errors encountered while preparing the import.
        /// </summary>
        public readonly string ImportCheckErrors;
        /// <summary>
        /// When the import started.
        /// </summary>
        public readonly string StartedAt;
        /// <summary>
        /// The state of the import, one of: pending, queued, in_progress, complete, cancelled, error.
        /// </summary>
        public readonly string State;

        [OutputConstructor]
        private GetDatabaseDataImportResult(
            Outputs.GetDatabaseDataImportDataSourceResult dataSource,

            string finishedAt,

            string importCheckErrors,

            string startedAt,

            string state)
        {
            DataSource = dataSource;
            FinishedAt = finishedAt;
            ImportCheckErrors = importCheckErrors;
            StartedAt = startedAt;
            State = state;
        }
    }
}
