// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Planetscale.Outputs
{

    [OutputType]
    public sealed class GetOrganizationFlagsResult
    {
        public readonly string ExampleFlag;

        [OutputConstructor]
        private GetOrganizationFlagsResult(string exampleFlag)
        {
            ExampleFlag = exampleFlag;
        }
    }
}
