// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Planetscale.Outputs
{

    [OutputType]
    public sealed class GetPasswordsPasswordDatabaseBranchResult
    {
        public readonly string AccessHostUrl;
        public readonly string Id;
        public readonly string MysqlEdgeAddress;
        public readonly string Name;
        public readonly bool Production;

        [OutputConstructor]
        private GetPasswordsPasswordDatabaseBranchResult(
            string accessHostUrl,

            string id,

            string mysqlEdgeAddress,

            string name,

            bool production)
        {
            AccessHostUrl = accessHostUrl;
            Id = id;
            MysqlEdgeAddress = mysqlEdgeAddress;
            Name = name;
            Production = production;
        }
    }
}
