# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetBranchSchemaResult',
    'AwaitableGetBranchSchemaResult',
    'get_branch_schema',
    'get_branch_schema_output',
]

@pulumi.output_type
class GetBranchSchemaResult:
    """
    A collection of values returned by getBranchSchema.
    """
    def __init__(__self__, branch=None, database=None, id=None, keyspace=None, organization=None, tables=None):
        if branch and not isinstance(branch, str):
            raise TypeError("Expected argument 'branch' to be a str")
        pulumi.set(__self__, "branch", branch)
        if database and not isinstance(database, str):
            raise TypeError("Expected argument 'database' to be a str")
        pulumi.set(__self__, "database", database)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if keyspace and not isinstance(keyspace, str):
            raise TypeError("Expected argument 'keyspace' to be a str")
        pulumi.set(__self__, "keyspace", keyspace)
        if organization and not isinstance(organization, str):
            raise TypeError("Expected argument 'organization' to be a str")
        pulumi.set(__self__, "organization", organization)
        if tables and not isinstance(tables, list):
            raise TypeError("Expected argument 'tables' to be a list")
        pulumi.set(__self__, "tables", tables)

    @property
    @pulumi.getter
    def branch(self) -> str:
        return pulumi.get(self, "branch")

    @property
    @pulumi.getter
    def database(self) -> str:
        return pulumi.get(self, "database")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def keyspace(self) -> Optional[str]:
        return pulumi.get(self, "keyspace")

    @property
    @pulumi.getter
    def organization(self) -> str:
        return pulumi.get(self, "organization")

    @property
    @pulumi.getter
    def tables(self) -> Sequence['outputs.GetBranchSchemaTableResult']:
        return pulumi.get(self, "tables")


class AwaitableGetBranchSchemaResult(GetBranchSchemaResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetBranchSchemaResult(
            branch=self.branch,
            database=self.database,
            id=self.id,
            keyspace=self.keyspace,
            organization=self.organization,
            tables=self.tables)


def get_branch_schema(branch: Optional[str] = None,
                      database: Optional[str] = None,
                      keyspace: Optional[str] = None,
                      organization: Optional[str] = None,
                      opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetBranchSchemaResult:
    """
    The schema of a PlanetScale branch.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_planetscale as planetscale

    example = planetscale.get_branch_schema(organization="example.com",
        database="example_db",
        branch="main")
    pulumi.export("branchSchema", example)
    ```
    """
    __args__ = dict()
    __args__['branch'] = branch
    __args__['database'] = database
    __args__['keyspace'] = keyspace
    __args__['organization'] = organization
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('planetscale:index/getBranchSchema:getBranchSchema', __args__, opts=opts, typ=GetBranchSchemaResult).value

    return AwaitableGetBranchSchemaResult(
        branch=pulumi.get(__ret__, 'branch'),
        database=pulumi.get(__ret__, 'database'),
        id=pulumi.get(__ret__, 'id'),
        keyspace=pulumi.get(__ret__, 'keyspace'),
        organization=pulumi.get(__ret__, 'organization'),
        tables=pulumi.get(__ret__, 'tables'))
def get_branch_schema_output(branch: Optional[pulumi.Input[str]] = None,
                             database: Optional[pulumi.Input[str]] = None,
                             keyspace: Optional[pulumi.Input[Optional[str]]] = None,
                             organization: Optional[pulumi.Input[str]] = None,
                             opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetBranchSchemaResult]:
    """
    The schema of a PlanetScale branch.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_planetscale as planetscale

    example = planetscale.get_branch_schema(organization="example.com",
        database="example_db",
        branch="main")
    pulumi.export("branchSchema", example)
    ```
    """
    __args__ = dict()
    __args__['branch'] = branch
    __args__['database'] = database
    __args__['keyspace'] = keyspace
    __args__['organization'] = organization
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('planetscale:index/getBranchSchema:getBranchSchema', __args__, opts=opts, typ=GetBranchSchemaResult)
    return __ret__.apply(lambda __response__: GetBranchSchemaResult(
        branch=pulumi.get(__response__, 'branch'),
        database=pulumi.get(__response__, 'database'),
        id=pulumi.get(__response__, 'id'),
        keyspace=pulumi.get(__response__, 'keyspace'),
        organization=pulumi.get(__response__, 'organization'),
        tables=pulumi.get(__response__, 'tables')))
