# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetOauthApplicationsResult',
    'AwaitableGetOauthApplicationsResult',
    'get_oauth_applications',
    'get_oauth_applications_output',
]

@pulumi.output_type
class GetOauthApplicationsResult:
    """
    A collection of values returned by getOauthApplications.
    """
    def __init__(__self__, applications=None, id=None, organization=None):
        if applications and not isinstance(applications, list):
            raise TypeError("Expected argument 'applications' to be a list")
        pulumi.set(__self__, "applications", applications)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if organization and not isinstance(organization, str):
            raise TypeError("Expected argument 'organization' to be a str")
        pulumi.set(__self__, "organization", organization)

    @property
    @pulumi.getter
    def applications(self) -> Sequence['outputs.GetOauthApplicationsApplicationResult']:
        return pulumi.get(self, "applications")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def organization(self) -> str:
        return pulumi.get(self, "organization")


class AwaitableGetOauthApplicationsResult(GetOauthApplicationsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetOauthApplicationsResult(
            applications=self.applications,
            id=self.id,
            organization=self.organization)


def get_oauth_applications(organization: Optional[str] = None,
                           opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetOauthApplicationsResult:
    """
    A list of PlanetScale OAuth applications. (requires feature flag)

    ## Example Usage

    ```python
    import pulumi
    import pulumi_planetscale as planetscale

    # requires a feature flag, contact support to enable it
    example = planetscale.get_oauth_applications(organization=example_planetscale_organization["name"])
    pulumi.export("oauthApps", example)
    ```
    """
    __args__ = dict()
    __args__['organization'] = organization
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('planetscale:index/getOauthApplications:getOauthApplications', __args__, opts=opts, typ=GetOauthApplicationsResult).value

    return AwaitableGetOauthApplicationsResult(
        applications=pulumi.get(__ret__, 'applications'),
        id=pulumi.get(__ret__, 'id'),
        organization=pulumi.get(__ret__, 'organization'))
def get_oauth_applications_output(organization: Optional[pulumi.Input[str]] = None,
                                  opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetOauthApplicationsResult]:
    """
    A list of PlanetScale OAuth applications. (requires feature flag)

    ## Example Usage

    ```python
    import pulumi
    import pulumi_planetscale as planetscale

    # requires a feature flag, contact support to enable it
    example = planetscale.get_oauth_applications(organization=example_planetscale_organization["name"])
    pulumi.export("oauthApps", example)
    ```
    """
    __args__ = dict()
    __args__['organization'] = organization
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('planetscale:index/getOauthApplications:getOauthApplications', __args__, opts=opts, typ=GetOauthApplicationsResult)
    return __ret__.apply(lambda __response__: GetOauthApplicationsResult(
        applications=pulumi.get(__response__, 'applications'),
        id=pulumi.get(__response__, 'id'),
        organization=pulumi.get(__response__, 'organization')))
