// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Planetscale.Inputs
{

    public sealed class GetDatabaseDataImportDataSourceArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the database imported from.
        /// </summary>
        [Input("database", required: true)]
        public string Database { get; set; } = null!;

        /// <summary>
        /// The hostname where the database lives.
        /// </summary>
        [Input("hostname", required: true)]
        public string Hostname { get; set; } = null!;

        /// <summary>
        /// The port on which the database listens on the host.
        /// </summary>
        [Input("port", required: true)]
        public string Port { get; set; } = null!;

        public GetDatabaseDataImportDataSourceArgs()
        {
        }
        public static new GetDatabaseDataImportDataSourceArgs Empty => new GetDatabaseDataImportDataSourceArgs();
    }
}
