// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Planetscale.Inputs
{

    public sealed class GetDatabaseDataImportInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Connection information for the source of the data for the import.
        /// </summary>
        [Input("dataSource", required: true)]
        public Input<Inputs.GetDatabaseDataImportDataSourceInputArgs> DataSource { get; set; } = null!;

        /// <summary>
        /// When the import finished.
        /// </summary>
        [Input("finishedAt", required: true)]
        public Input<string> FinishedAt { get; set; } = null!;

        /// <summary>
        /// Errors encountered while preparing the import.
        /// </summary>
        [Input("importCheckErrors", required: true)]
        public Input<string> ImportCheckErrors { get; set; } = null!;

        /// <summary>
        /// When the import started.
        /// </summary>
        [Input("startedAt", required: true)]
        public Input<string> StartedAt { get; set; } = null!;

        /// <summary>
        /// The state of the import, one of: pending, queued, in_progress, complete, cancelled, error.
        /// </summary>
        [Input("state", required: true)]
        public Input<string> State { get; set; } = null!;

        public GetDatabaseDataImportInputArgs()
        {
        }
        public static new GetDatabaseDataImportInputArgs Empty => new GetDatabaseDataImportInputArgs();
    }
}
