// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Planetscale.Inputs
{

    public sealed class GetDatabaseDataImportDataSourceInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the database imported from.
        /// </summary>
        [Input("database", required: true)]
        public Input<string> Database { get; set; } = null!;

        /// <summary>
        /// The hostname where the database lives.
        /// </summary>
        [Input("hostname", required: true)]
        public Input<string> Hostname { get; set; } = null!;

        /// <summary>
        /// The port on which the database listens on the host.
        /// </summary>
        [Input("port", required: true)]
        public Input<string> Port { get; set; } = null!;

        public GetDatabaseDataImportDataSourceInputArgs()
        {
        }
        public static new GetDatabaseDataImportDataSourceInputArgs Empty => new GetDatabaseDataImportDataSourceInputArgs();
    }
}
