// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Planetscale.Inputs
{

    public sealed class PasswordDatabaseBranchGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("accessHostUrl")]
        public Input<string>? AccessHostUrl { get; set; }

        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("mysqlEdgeAddress")]
        public Input<string>? MysqlEdgeAddress { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("production")]
        public Input<bool>? Production { get; set; }

        public PasswordDatabaseBranchGetArgs()
        {
        }
        public static new PasswordDatabaseBranchGetArgs Empty => new PasswordDatabaseBranchGetArgs();
    }
}
